### ISSUE TITLE
BIDS-examples/ds001: nifti files do not get a filename when uploaded

### ISSUE THREAD

**Issue by ehlertjd** [flywheel-io/bids-client#2]
I think this has to do with template or filename matching. The only data that gets populated is:
```json
{"RepetitionTime":2,"TaskName":"balloon analog risk task"}
```

**Comment by LinaJohnson** [comment]
**Summary of Issue**
Some BIDS objects don't include the `Filename` attribute. May be an issue with the imported test data. In the example below all of the listed items are `BIDS` objects, however the highlighted 3 are missing the `Filename` attribute. 
<img width="789" alt="screen shot 2018-01-10 at 11 15 32 am" src="https://user-images.githubusercontent.com/12104092/34786807-c9b6ae4c-f5fa-11e7-9ef0-efd72da0803b.png">

**Solution**
There should always be a `Filename` attribute on the BIDS objects. For now, I've created a fall back that will call the pre-existing `{{ file.name }}` if the `{{ file.info.BIDS.Filename }}` is missing.

**Comment by LinaJohnson** [comment]
@ehlertjd it's not specific to just nifti files since the top two BIDS objects have `Filename`.

**Comment by hkethi002** [comment]
I think I may have found where this bug comes from: the correct BIDS info is uploaded but then overwritten with the info from the sidecar json files that is in the project folder, when the additional info is added, the originally uploaded info needs to be in the payload as well for the modifying file info api endpoint.

**Comment by ehlertjd** [comment]
Closed via #4.
